### ISSUE TITLE
Min API version

### ISSUE THREAD

**Issue by FlipDev** [Euzee/serviceManager#3]
Why you are using 19+?  I make compilation with minSdkVersion 14 and all works fine. Plz make changes.

**Comment by Euzee** [comment]
@FlipDev Hello. Yes it is not a problem ( that was just copied from previous project) .

**Comment by Euzee** [comment]
@FlipDev updated in 1.0.2

**Comment by Euzee** [comment]
@FlipDev updated in 1.0.2
