### ISSUE TITLE
few moment of import of library

### ISSUE THREAD

**Issue by transportnik** [Euzee/serviceManager#5]
Firstly library is great! But please add few moment for instructions of import:
1. When I was trying make build of project I have got an exсeption related with project settings.
During of installation of library we should check Source Compatibly and Target Compatibly settings it must be not empty and better if it will be 1.8
2. Please check why project during of making of build give an exception related with android manifest and concretely is related with parameter: android:allowBackup="true"
For successful making of build it must be "false". 
Thank you.

**Comment by transportnik** [comment]
And one more moment of import as I understand when we use your library we can not use usual IntentService because  your service with android version less than Oreo work like usual IntentService? If yes it important write it in import instructions

**Comment by Euzee** [comment]
> And one more moment of import as I understand when we use your library we can not use usual IntentService because your service with android version less than Oreo work like usual IntentService? If yes it important write it in import instructions 

there is section  after example with GeofenceTransitionsIntentService: 
In order to use it as last two ways - your service should extend CompatService
`public abstract class CompatService extends JobIntentService`

**Comment by Euzee** [comment]
> Please check why project during of making of build give an exception related with android manifest and concretely is related with parameter: android:allowBackup="true"
For successful making of build it must be "false". 

This is because of settings for backup in manyfest : 
https://github.com/Euzee/serviceManager/blob/master/serviceManager/src/main/AndroidManifest.xml 
You can replace them in your project  with 
` tools:replace="android:allowBackup"`

**Comment by Euzee** [comment]
Removed unused parameters from manifest. 
But still build with java 1.8
