### ISSUE TITLE
min sdk api > 26

### ISSUE THREAD

**Issue by KORuL** [Euzee/serviceManager#7]
How to use this lybrary in api < 26

**Comment by Euzee** [comment]
Hello. 
Just as described : 
`ServiceManager.runService(context, () -> {Logg.e(TAG,"Some Action");},true);`  

This is example with lambda ( you need to set options to use lambda ) : 
```
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    } 
 ```

**Comment by KORuL** [comment]
To set this option need api > 26
